### ISSUE TITLE
Error encoding on Windows 

### ISSUE THREAD

**Issue by jackch1** [master-of-zen/Av1an#10]
I'm pretty new to this, but I've checked all the install requirements etc and I'm still getting this error when trying to encode. 

`C:\Av1an>av1an.py -i Sintel_1080p_YUV_RAW.avi  -enc svt_av1 -e "-w 1920 -h 818 -fps 24"
'ffprobe' is not recognized as an internal or external command,
operable program or batch file.
'scenedetect' is not recognized as an internal or external command,
operable program or batch file.
Video Sintel_1080p_YUV_RAW.avi splitted
Splited videos: 0
Starting encoding with 0 workers.
Parameters: -w 1920 -h 818 -fps 24
Encoding..
|---------------------------------------------------------------------------------------------------------| 0% 0/0 Traceback (most recent call last):
  File "C:\Av1an\av1an.py", line 406, in <module>
    av1an.main()
  File "C:\Av1an\av1an.py", line 393, in main
    pool = Pool(self.workers)
  File "C:\Users\jackc\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\jackc\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1`

I have installed scenedetect and ffmpeg successfully so not sure what is causing this.

A bug or my error?

**Comment by master-of-zen** [comment]
Couple of thing can be wrong:
1. FFmpeg with no ffprobe.
2. Both programs don't set in you environment PATH https://stackoverflow.com/questions/48321639/is-not-recognized-as-an-internal-or-external-command-operable-program-or-bat

**Comment by jackch1** [comment]
Thanks for the reply, I put the other executables in the same folder as Av1an and that fixed the errors. I'm still running into this error, encoding with zero workers. Any ideas?

```
C:\Av1an>av1an.py -i Sintel_1080p_YUV_RAW.avi -enc svt_av1 -e "-w 1920 -h 818 -fps 24"
[PySceneDetect] Output directory set:
  C:\Av1an\.temp\split
[PySceneDetect] Loaded 1 video, framerate: 24.00 FPS, resolution: 1920 x 818
[PySceneDetect] Downscale factor set to 6, effective resolution: 320 x 136
[PySceneDetect] Scene list CSV file name format:
  $VIDEO_NAME-Scenes.csv
[PySceneDetect] Video output file name format: $VIDEO_NAME-Scene-$SCENE_NUMBER
[PySceneDetect] Detecting scenes...
100%|███████████████████████████████████████████████████████████████████████████| 784/784 [00:06<00:00, 115.44frames/s]
[PySceneDetect] Processed 784 frames in 6.8 seconds (average 115.29 FPS).
[PySceneDetect] Detected 7 scenes, average shot length 4.7 seconds.
[PySceneDetect] Writing scene list to CSV file:
  C:\Av1an\.temp\split\Sintel_1080p_YUV_RAW-Scenes.csv
[PySceneDetect] Scene List:
-----------------------------------------------------------------------
 | Scene # | Start Frame |  Start Time  |  End Frame  |   End Time   |
-----------------------------------------------------------------------
 |      1  |           0 | 00:00:00.000 |         127 | 00:00:05.292 |
 |      2  |         127 | 00:00:05.292 |         277 | 00:00:11.542 |
 |      3  |         277 | 00:00:11.542 |         621 | 00:00:25.875 |
 |      4  |         621 | 00:00:25.875 |         648 | 00:00:27.000 |
 |      5  |         648 | 00:00:27.000 |         709 | 00:00:29.542 |
 |      6  |         709 | 00:00:29.542 |         755 | 00:00:31.458 |
 |      7  |         755 | 00:00:31.458 |         784 | 00:00:32.667 |
-----------------------------------------------------------------------

[PySceneDetect] Comma-separated timecode list:
  00:00:05.292,00:00:11.542,00:00:25.875,00:00:27.000,00:00:29.542,00:00:31.458
[PySceneDetect] Splitting input video using mkvmerge, output path template:
  C:\Av1an\.temp\split\$VIDEO_NAME-Scene-$SCENE_NUMBER.mkv
[PySceneDetect] Average processing speed 171.25 frames/sec.
[PySceneDetect] Video splitting completed, individual scenes written to disk.
Video Sintel_1080p_YUV_RAW.avi splitted
Splited videos: 7
Starting encoding with 0 workers.
Parameters: -w 1920 -h 818 -fps 24
Encoding..
|---------------------------------------------------------------------------------------------------------| 0% 0/7 Traceback (most recent call last):
  File "C:\Av1an\av1an.py", line 406, in <module>
    av1an.main()
  File "C:\Av1an\av1an.py", line 393, in main
    pool = Pool(self.workers)
  File "C:\Users\jackc\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\jackc\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by master-of-zen** [comment]
Try setting workers manually with -t 1. I think it can be error in determining number of workers, i set it really aggressive for SVT-AV1 because it can have 6+ threads load and 6GB+ of memory per encoder. Which means that it can be easily rounded up to 0.

**Comment by jackch1** [comment]
Setting the workers manually worked, but now the encoding is failing. I've tried .yuv, .avi, .mkv with files that work in SVTAV1encApp but no luck in Av1an. 

```
C:\Av1an1.0>av1an.py -i "D:\Source\Sintel\1080pAVI\Sintel_1080p_RGB_CROP.avi" -enc svt_av1 -fps 24 -fmt yuv420p -e " -fps 24 -w 1920 -h 816 -rc 2 -tbr 1000 -enc-mode 5" -o "D:\Compressed Outputs\SVT-AV1\Sintel_1080_1000.ivf" -t 1
[PySceneDetect] Output directory set:
  C:\Av1an1.0\.temp\split
[PySceneDetect] Loaded 1 video, framerate: 24.00 FPS, resolution: 1920 x 816
[PySceneDetect] Downscale factor set to 6, effective resolution: 320 x 136
[PySceneDetect] Scene list CSV file name format:
  $VIDEO_NAME-Scenes.csv
[PySceneDetect] Video output file name format: $VIDEO_NAME-Scene-$SCENE_NUMBER
[PySceneDetect] Detecting scenes...
100%|███████████████████████████████████████████████████████████████████████████| 720/720 [00:06<00:00, 116.22frames/s]
[PySceneDetect] Processed 720 frames in 6.2 seconds (average 116.07 FPS).
[PySceneDetect] Detected 6 scenes, average shot length 5.0 seconds.
[PySceneDetect] Writing scene list to CSV file:
  C:\Av1an1.0\.temp\split\Sintel_1080p_RGB_CROP-Scenes.csv
[PySceneDetect] Scene List:
-----------------------------------------------------------------------
 | Scene # | Start Frame |  Start Time  |  End Frame  |   End Time   |
-----------------------------------------------------------------------
 |      1  |           0 | 00:00:00.000 |         127 | 00:00:05.292 |
 |      2  |         127 | 00:00:05.292 |         277 | 00:00:11.542 |
 |      3  |         277 | 00:00:11.542 |         621 | 00:00:25.875 |
 |      4  |         621 | 00:00:25.875 |         648 | 00:00:27.000 |
 |      5  |         648 | 00:00:27.000 |         709 | 00:00:29.542 |
 |      6  |         709 | 00:00:29.542 |         720 | 00:00:30.000 |
-----------------------------------------------------------------------

[PySceneDetect] Comma-separated timecode list:
  00:00:05.292,00:00:11.542,00:00:25.875,00:00:27.000,00:00:29.542
[PySceneDetect] Splitting input video using mkvmerge, output path template:
  C:\Av1an1.0\.temp\split\$VIDEO_NAME-Scene-$SCENE_NUMBER.mkv
[PySceneDetect] Average processing speed 168.94 frames/sec.
[PySceneDetect] Video splitting completed, individual scenes written to disk.
Video D:\Source\Sintel\1080pAVI\Sintel_1080p_RGB_CROP.avi splitted
Splited videos: 6
Starting encoding with 1 workers.
Parameters:  -fps 24 -w 1920 -h 816 -rc 2 -tbr 1000 -enc-mode 5
Encoding..
|---------------------------------------------------------------------------------------------------------| 0% 0/6 Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
|█████████████████----------------------------------------------------------------------------------------| 16.7% 1/6 Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
|███████████████████████████████████----------------------------------------------------------------------| 33.3% 2/6 Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
|████████████████████████████████████████████████████-----------------------------------------------------| 50.0% 3/6 Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
|██████████████████████████████████████████████████████████████████████-----------------------------------| 66.7% 4/6 Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
|███████████████████████████████████████████████████████████████████████████████████████------------------| 83.3% 5/6 Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error instance 1: Input yuv does not contain enough frames
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% 6/6 [matroska,webm @ 0000023d46063740] EBML header parsing failed
[concat @ 0000023d4605a000] Impossible to open 'C:\Av1an1.0\.temp\encode\Sintel_1080p_RGB_CROP-Scene-001.mkv'
C:\Av1an1.0\.temp\concat.txt: Invalid data found when processing input

Completed in 15.0 seconds
```

**Comment by master-of-zen** [comment]
Find out that on Windows SVT-AV1 have problem with pipes.
`Error instance 1: Input yuv does not contain enough frames`
https://www.reddit.com/r/AV1/comments/cmwe6b/named_pipes_with_svtav1_and_rav1e/
https://gitmemory.com/issue/OpenVisualCloud/SVT-AV1/523/527549440
https://github.com/OpenVisualCloud/SVT-AV1/pull/581
Mb it not fixed yet

**Comment by master-of-zen** [comment]
is other encoders works?
