### ISSUE TITLE
Source files with spaces in the filename causes it to attempt to run with 0 workers.

### ISSUE THREAD

**Issue by nathanielcwm** [master-of-zen/Av1an#14]
If there are spaces in the source name the script seems to set the workers to 0, this obviously causes it to error out.
```python
av1an.py -i "file with spaces.mp4" --encoder svt_av1 -e '-w 1920 -h 1080 -fps 29' -fmt yuv420p10le
Clips:0 Workers: 0
Params: -w 1920 -h 1080 -fps 29
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| 0% 0/0 Traceback (most recent call last):
  File "/home/nathanielcwm/Av1an//av1an.py", line 450, in <module>
    av1an.main()
  File "/home/nathanielcwm/Av1an//av1an.py", line 431, in main
    pool = Pool(self.workers)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by master-of-zen** [comment]
Path should be without spaces, that general rule for basically everything :)
