### ISSUE TITLE
svt_vp9 encoder parameter causes failure

### ISSUE THREAD

**Issue by kozross** [master-of-zen/Av1an#158]
Basically, this speaks for itself:

```
[koz@Emi ~]$ av1an --input gundam-wing-01.mkv --output_file test --encoder svt_vp9 --workers 8
Traceback (most recent call last):
  File "/usr/bin/av1an", line 33, in <module>
    sys.exit(load_entry_point('Av1an==1.13.post3', 'console_scripts', 'av1an')())
  File "/usr/lib/python3.8/site-packages/av1an.py", line 18, in main
    Av1an().main_thread()
  File "/usr/lib/python3.8/site-packages/av1an.py", line 13, in main_thread
    startup_check(self.args)
  File "/usr/lib/python3.8/site-packages/Startup/setup.py", line 94, in startup_check
    check_exes(args)
  File "/usr/lib/python3.8/site-packages/Startup/setup.py", line 52, in check_exes
    validate_inputs(args)
  File "/usr/lib/python3.8/site-packages/Startup/validate_commands.py", line 65, in validate_inputs
    video_params = [x.split('=')[0] for x in video_params if not x.isdigit()]
TypeError: 'NoneType' object is not iterable
```

**Comment by n9Mtq4** [comment]
SVT-VP9 needs `-v " -w [video width] -h [video height] -fps [framerate]"` to work.

We'll add a more friendly error message to this.
