### ISSUE TITLE
Error when Installing Av1an

### ISSUE THREAD

**Issue by dexeonify** [master-of-zen/Av1an#161]
I'm running into issues when installing Av1an. I tried both methods and they are both giving me errors.
I have the latest version of Python (Python 3.8.6, x64) and the latest FFmpeg Windows build from [here](https://www.gyan.dev/ffmpeg/builds/).

Windows x64
Windows Update: 2004
Windows Build Version: 19041.508

### With a package manager (PyPi)
`pip install Av1an ` returns the following error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2741, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'progress_bar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 331, in _get_abstract_dist_for
    skip_reason = self._check_skip_installed(req)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 236, in _check_skip_installed
    req_to_install.check_if_exists(self.use_user_site)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\req\req_install.py", line 433, in check_if_exists
    existing_dist = get_distribution(self.req.name)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\utils\misc.py", line 531, in get_distribution
    pkg_resources.working_set.require(req_name)
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 794, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2743, in requires
    raise UnknownExtra(
pip._vendor.pkg_resources.UnknownExtra: scenedetect 0.5.4.1 has no such extra feature 'progress_bar'
```

### Manual Install
After downloading from releases, running `python setup.py install` in terminal returns the following error:

```
C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py:458: UserWarning: Normalizing '1.13-3' to '1.13.post3'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
creating Av1an.egg-info
writing Av1an.egg-info\PKG-INFO
writing dependency_links to Av1an.egg-info\dependency_links.txt
writing entry points to Av1an.egg-info\entry_points.txt
writing requirements to Av1an.egg-info\requires.txt
writing top-level names to Av1an.egg-info\top_level.txt
writing manifest file 'Av1an.egg-info\SOURCES.txt'
reading manifest file 'Av1an.egg-info\SOURCES.txt'
writing manifest file 'Av1an.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
copying av1an.py -> build\lib
creating build\lib\Av1an
copying Av1an\arg_parse.py -> build\lib\Av1an
copying Av1an\bar.py -> build\lib\Av1an
copying Av1an\commandtypes.py -> build\lib\Av1an
copying Av1an\concat.py -> build\lib\Av1an
copying Av1an\config.py -> build\lib\Av1an
copying Av1an\encode.py -> build\lib\Av1an
copying Av1an\ffmpeg.py -> build\lib\Av1an
copying Av1an\fp_reuse.py -> build\lib\Av1an
copying Av1an\logger.py -> build\lib\Av1an
copying Av1an\resume.py -> build\lib\Av1an
copying Av1an\split.py -> build\lib\Av1an
copying Av1an\utils.py -> build\lib\Av1an
copying Av1an\__init__.py -> build\lib\Av1an
creating build\lib\Chunks
copying Chunks\chunk.py -> build\lib\Chunks
copying Chunks\chunk_queue.py -> build\lib\Chunks
copying Chunks\__init__.py -> build\lib\Chunks
creating build\lib\Encoders
copying Encoders\aom.py -> build\lib\Encoders
copying Encoders\encoder.py -> build\lib\Encoders
copying Encoders\rav1e.py -> build\lib\Encoders
copying Encoders\svtav1.py -> build\lib\Encoders
copying Encoders\svtvp9.py -> build\lib\Encoders
copying Encoders\vpx.py -> build\lib\Encoders
copying Encoders\vvc.py -> build\lib\Encoders
copying Encoders\x264.py -> build\lib\Encoders
copying Encoders\x265.py -> build\lib\Encoders
copying Encoders\__init__.py -> build\lib\Encoders
creating build\lib\Scenedetection
copying Scenedetection\aom_kf.py -> build\lib\Scenedetection
copying Scenedetection\pyscene.py -> build\lib\Scenedetection
copying Scenedetection\__init__.py -> build\lib\Scenedetection
creating build\lib\Startup
copying Startup\setup.py -> build\lib\Startup
copying Startup\validate_commands.py -> build\lib\Startup
copying Startup\__init__.py -> build\lib\Startup
creating build\lib\VMAF
copying VMAF\target_vmaf.py -> build\lib\VMAF
copying VMAF\vmaf.py -> build\lib\VMAF
copying VMAF\__init__.py -> build\lib\VMAF
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\arg_parse.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\bar.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\commandtypes.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\concat.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\config.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\encode.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\ffmpeg.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\fp_reuse.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\logger.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\resume.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\split.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\utils.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\Av1an\__init__.py -> build\bdist.win-amd64\egg\Av1an
copying build\lib\av1an.py -> build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\Chunks
copying build\lib\Chunks\chunk.py -> build\bdist.win-amd64\egg\Chunks
copying build\lib\Chunks\chunk_queue.py -> build\bdist.win-amd64\egg\Chunks
copying build\lib\Chunks\__init__.py -> build\bdist.win-amd64\egg\Chunks
creating build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\aom.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\encoder.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\rav1e.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\svtav1.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\svtvp9.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\vpx.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\vvc.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\x264.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\x265.py -> build\bdist.win-amd64\egg\Encoders
copying build\lib\Encoders\__init__.py -> build\bdist.win-amd64\egg\Encoders
creating build\bdist.win-amd64\egg\Scenedetection
copying build\lib\Scenedetection\aom_kf.py -> build\bdist.win-amd64\egg\Scenedetection
copying build\lib\Scenedetection\pyscene.py -> build\bdist.win-amd64\egg\Scenedetection
copying build\lib\Scenedetection\__init__.py -> build\bdist.win-amd64\egg\Scenedetection
creating build\bdist.win-amd64\egg\Startup
copying build\lib\Startup\setup.py -> build\bdist.win-amd64\egg\Startup
copying build\lib\Startup\validate_commands.py -> build\bdist.win-amd64\egg\Startup
copying build\lib\Startup\__init__.py -> build\bdist.win-amd64\egg\Startup
creating build\bdist.win-amd64\egg\VMAF
copying build\lib\VMAF\target_vmaf.py -> build\bdist.win-amd64\egg\VMAF
copying build\lib\VMAF\vmaf.py -> build\bdist.win-amd64\egg\VMAF
copying build\lib\VMAF\__init__.py -> build\bdist.win-amd64\egg\VMAF
byte-compiling build\bdist.win-amd64\egg\Av1an\arg_parse.py to arg_parse.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\bar.py to bar.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\commandtypes.py to commandtypes.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\concat.py to concat.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\config.py to config.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\encode.py to encode.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\ffmpeg.py to ffmpeg.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\fp_reuse.py to fp_reuse.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\logger.py to logger.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\resume.py to resume.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\split.py to split.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\utils.py to utils.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Av1an\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\av1an.py to av1an.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Chunks\chunk.py to chunk.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Chunks\chunk_queue.py to chunk_queue.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Chunks\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\aom.py to aom.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\encoder.py to encoder.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\rav1e.py to rav1e.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\svtav1.py to svtav1.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\svtvp9.py to svtvp9.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\vpx.py to vpx.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\vvc.py to vvc.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\x264.py to x264.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\x265.py to x265.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Encoders\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Scenedetection\aom_kf.py to aom_kf.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Scenedetection\pyscene.py to pyscene.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Scenedetection\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Startup\setup.py to setup.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Startup\validate_commands.py to validate_commands.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\Startup\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\VMAF\target_vmaf.py to target_vmaf.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\VMAF\vmaf.py to vmaf.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\VMAF\__init__.py to __init__.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying Av1an.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying Av1an.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Av1an.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Av1an.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Av1an.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying Av1an.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\Av1an-1.13.post3-py3.8.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing Av1an-1.13.post3-py3.8.egg
Copying Av1an-1.13.post3-py3.8.egg to c:\users\blob\appdata\local\programs\python\python38\lib\site-packages
Adding Av1an 1.13.post3 to easy-install.pth file
Installing av1an-script.py script to C:\Users\Blob\AppData\Local\Programs\Python\Python38\Scripts
Installing av1an.exe script to C:\Users\Blob\AppData\Local\Programs\Python\Python38\Scripts

Installed c:\users\blob\appdata\local\programs\python\python38\lib\site-packages\av1an-1.13.post3-py3.8.egg
Processing dependencies for Av1an==1.13.post3
Traceback (most recent call last):
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2750, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'progress_bar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setuptools.setup(
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 667, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 714, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\easy_install.py", line 758, in process_distribution
    distros = WorkingSet([]).resolve(
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 793, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 2752, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: scenedetect 0.5.4.1 has no such extra feature 'progress_bar'
```

**Comment by master-of-zen** [comment]
Av1an no longer have progress_bar in for scenedetect in requirements.
If av1an was installed before, I recommend reinstalling it `pip uninstall av1an` -> `pip install av1an`

**Comment by dexeonify** [comment]
`pip uninstall av1an` was throwing the same errors as `pip install av1an`, but I got it fixed by running `pip uninstall scenedetect` and now I can proceed with the installation. 
During the installation, the terminal returns `ModuleNotFoundError: No module named 'fuzzywuzzy'`, so I assume you have to install fuzzywuzzy too?

Anyways I installed that and everything is working fine. Thanks!
