### ISSUE TITLE
[feature request] Vapoursynth script as source

### ISSUE THREAD

**Issue by gersch07** [master-of-zen/Av1an#222]
First of all, thanks a lot for this great work!

One thing I'd find useful would be if a Vapoursynth script could be loaded instead of a source video file. Currently I have to transcode my Vapoursynth scripts to intermediate FFV1 MKVs using ffmpeg, and these files take up a lot of space.
In case the option to load vpy scripts already exists, a short note in the documentation would be very helpful.

**Comment by lastrosade** [comment]
This could help with #221 by using imwri

**Comment by adworacz** [comment]
I added support for this months ago, and have been using it personally just fine. 

I’m a little out of date from the latest commits, so if it’s not working now there’s a new bug. 

Have you tried feeding the vpy script as the input file? It should be detected and handled correctly.

**Comment by adworacz** [comment]
Okay - looks like this *is* broken right now.

I believe that this is the offending line:
https://github.com/adworacz/Av1an/blob/478274a43acc8108bfd1c3433da036d1f98f5232/av1an/startup/setup.py#L88

@master-of-zen Not sure why this line was commented out. Is there a refactor going on, or was this just a temporary change that slipped through?

**Comment by master-of-zen** [comment]
@adworacz It probably was a time when I was making vapoursynth by default frame selection and probing method.
My bad

**Comment by adworacz** [comment]
Solid  I see you made some commits to fix - I'll give a test of the latest commit this weekend to confirm it works.

**Comment by adworacz** [comment]
Looks like things aren't quite fixed yet - using my above test file, the get the following exception stacktrace:
```
WARNING: Invalid params:
'--no-sao' isn't a valid param for x265. Did you mean '--sar'?
'--deblock' isn't a valid param for x265. Did you mean '--rect'?
'-1:-1' isn't a valid param for x265. Did you mean '-1'?
'--psy-rd' isn't a valid param for x265. Did you mean '--rd'?
'--psy-rdoq' isn't a valid param for x265. Did you mean '--rd'?
0frames [00:00, ?frames/s]Output 240 frames in 0.40 seconds (602.55 fps)
Traceback (most recent call last):
  File "/home/user/src/Av1an/av1an.py", line 5, in <module>
    main()
  File "/home/user/src/Av1an/av1an/__main__.py", line 14, in main
    manager.run()
  File "/home/user/src/Av1an/av1an/manager/Manager.py", line 64, in run
    EncodingManager().encode_file(proj)
  File "/home/user/src/Av1an/av1an/manager/Manager.py", line 90, in encode_file
    split_locations = split_routine(project, project.resume)
  File "/home/user/src/Av1an/av1an/split.py", line 54, in split_routine
    write_scenes_to_file(scenes, project.get_frames(), scene_file)
  File "/home/user/src/Av1an/av1an/project/Project.py", line 106, in get_frames
    fr = frame_probe_vspipe(vs)
  File "/home/user/src/Av1an/av1an/vapoursynth.py", line 23, in frame_probe_vspipe
    frames = int(matches[-1])
IndexError: list index out of range
0frames [00:00, ?frames/s]
```

**Comment by shssoichiro** [comment]
This seems to have returned somehow. I'm getting the same error with the latest git master:

```
Traceback (most recent call last):
  File "/usr/bin/av1an", line 33, in <module>
    sys.exit(load_entry_point('Av1an==6.1.post2', 'console_scripts', 'av1an')())
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/__main__.py", line 14, in main
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/manager/Manager.py", line 64, in run
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/manager/Manager.py", line 90, in encode_file
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/split.py", line 48, in split_routine
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/split.py", line 178, in calc_split_locations
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/scenedetection/aom_kf.py", line 227, in aom_keyframes
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/utils.py", line 78, in frame_probe_fast
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/utils.py", line 91, in frame_probe
  File "/usr/lib/python3.9/site-packages/Av1an-6.1.post2-py3.9.egg/av1an/vapoursynth.py", line 23, in frame_probe_vspipe
IndexError: list index out of range
```

I've tried installing both from AUR (`python-av1an-git`) and manually from git.

**Comment by shssoichiro** [comment]
Turns out this happens if the vpy filename has a space in it. I'll open a PR to fix.
