### ISSUE TITLE
Zombie vspipe processes

### ISSUE THREAD

**Issue by Nestorfish** [master-of-zen/Av1an#324]
Using VMAF mode, vspipe processes used during encoding with VMAF probing are left as zombies.

I suppose it was the root cause of the following error during a encode:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', av1an-core/src/lib.rs:689:10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/lib.rs:1682:21
```
Hopefully, it can be resumed with `-r`.

Example not so long time after resume:
```
 |   |   \-+= 18833 user av1an -i input.mkv -o output.mkv --vmaf-path /Users/user/Downloads/Video/vmaf_v0.6.1.json --target-quality 90 --vmaf -r -w 3
 |   |     |--- 18899 user (vspipe)
 |   |     |--- 18911 user (vspipe)
 |   |     |--- 18923 user (vspipe)
[lots of these...]
 |   |     |--- 25721 user (vspipe)
 |   |     |--- 25771 user (vspipe)
 |   |     |--- 25801 user (vspipe)
 |   |     |--- 25901 user vspipe .1f0147a/split/loadscript.vpy -y - -s 164433 -e 164564
 |   |     |--- 25907 user ffmpeg -y -hide_banner -loglevel error -i - -strict -1 -pix_fmt yuv420p10le -f yuv4mpegpipe -
 |   |     |--- 25913 user aomenc --passes=2 --pass=2 --threads=8 -b 10 --cpu-used=6 --end-usage=q --cq-level=24 --tile-columns=2 --tile-rows=1 --fpf=.1f0147a/split/01071_fpf.log -o .1f0147a/encode/01071.ivf -
```
OS: `macOS Big Sur`
Chunk method: `ffms2`
Command: `av1an -i input.mkv -o output.mkv --vmaf-path /Users/user/Downloads/Video/vmaf_v0.6.1.json --target-quality 90 --vmaf`

Note: initial ffmpeg command used to feed av1an for scene detection also stays as a zombie, it may be easier to start looking here.

**Comment by aswild** [comment]
Based on a quick glance of the source code, it looks like there's several instances of `Command::spawn()` getting called, the stdin/stdout pipes are taken out and then the `Child` object is ignored and dropped. Neither `std::process::Command` nor `tokio::process::Command` will wait for or kill a child process on drop, so these stack up as zombies.

Only commands where av1an waits for their output (e.g. with `wait_with_output()`) do the children actually get waited on and reaped on Unix OSes.

A relatively nonintrusive fix could be to simply spawn a background thread/task (depending on whether we're in a tokio context) that takes over the `Child` and waits for it in the background.
