### ISSUE TITLE
Encoding immediately fails with "IndexError: list index out of range"

### ISSUE THREAD

**Issue by datenbauer** [master-of-zen/Av1an#370]
I have installed the newest version of Av1an (through Pip), Vapoursynth + ffms2, libaom.
When I try to encode different video files, I always get this error:

```
[user@machine]$ av1an -i sample.mkv -v " --cpu-used=4 --end-usage=q --cq-level=30 --threads=4 " -w 1 --target_quality 95 -log av1an.log
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 66826/66832 [01:46<00:00, 629.80frames/s]
Traceback (most recent call last):
  File "/home/user/.local/bin/av1an", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/av1an/__main__.py", line 14, in main
    manager.run()
  File "/home/user/.local/lib/python3.9/site-packages/av1an/manager/Manager.py", line 65, in run
    EncodingManager().encode_file(proj)
  File "/home/user/.local/lib/python3.9/site-packages/av1an/manager/Manager.py", line 91, in encode_file
    split_locations = split_routine(project, project.resume)
  File "/home/user/.local/lib/python3.9/site-packages/av1an/split.py", line 53, in split_routine
    write_scenes_to_file(scenes, project.get_frames(), scene_file)
  File "/home/user/.local/lib/python3.9/site-packages/av1an/project/Project.py", line 110, in get_frames
    fr = frame_probe_vspipe(vs)
  File "/home/user/.local/lib/python3.9/site-packages/av1an/vapoursynth.py", line 24, in frame_probe_vspipe
    frames = int(matches[-1])
IndexError: list index out of range
```

This is the content of the log file:
```
[13:27:26] Set Chunking Method: FFMS2
[13:27:26] File hash: 1e379089
[13:27:26] Av1an Started
[13:27:26] Command:
[13:27:26] /home/user/.local/bin/av1an -i sample.mkv -v  --cpu-used=4 --end-usage=q --cq-level=30 --threads=4  -w 1 --target_quality 95 -log av1an.log
[13:27:26] Starting scene detection Threshold: 35, Min_scene_length: 60
[13:27:26] Starting PySceneDetect:
[13:27:26] Threshold: 35
[13:27:26] Min scene length: 60
[13:27:26] Is Vapoursynth input: False
[13:27:34] Found scenes: 7
```

Any ideas?

**Comment by datenbauer** [comment]
Problem solved: There were still conflicting library files from a previous installation. Deleting them solved the problem.
