### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by neoOpus** [master-of-zen/Av1an#466]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core\src\settings.rs:961:21

**Comment by redzic** [comment]
@neoOpus Can you please post the output of `av1an --version` and your full command line options that you used when this happened?

**Comment by neoOpus** [comment]
INFO [av1an_core::settings] temporary directory: C:\Users\neoop\Downloads\Nmkoder\data\av1anTemp\1640236162720
Scene detection
INFO [av1an_core::settings] scenecut: found 7 scene(s) [with extra_splits(240 frames): 306]
00:07:02 [#####################################################################] 100%  72715/72715 (171.96 fps, eta 0s)
Queue 306 Workers 4 Passes 1
Params: --preset 5 --crf 20 --keyint 480 --lp 2 --film-grain 0 --tile-rows 1 --tile-columns 0
[Worker 1] Svt[info]: -------------------------------------------
00:00:03 [------------------------------------------------------------------------------]   0%  0/72715 (0 fps, eta 0s)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1094995529: Invalid data found when processing input)', av1an-core\src\broker.rs:250:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Worker 1] Svt[info]: -------------------------------------------
[Worker 2] Svt[info]: -------------------------------------------
[Worker 1] Svt[info]: -------------------------------------------
[Worker 2] Svt[info]: -------------------------------------------
[Worker 1] Svt[info]: -------------------------------------------
[Worker 2] Svt[info]: -------------------------------------------
[Worker 3] Svt[info]: -------------------------------------------
[Worker 4] Svt[info]: -------------------------------------------
04:28:37 [###############>--------------------------]  37%  26545/72715 (1.65 fps, eta 8h, 1247.6 Kbps, est. 180.25MiB)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1094995529: Invalid data found when processing input)', av1an-core\src\broker.rs:250:70
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core\src\settings.rs:994:21

[process exited with code 101]

**Comment by neoOpus** [comment]
I'm using AV1an with NMKODER

**Comment by redzic** [comment]
Did you replace the SVT-AV1 binary that came with nmkoder with the 0.8.8 version?

**Comment by neoOpus** [comment]
No I downloaded the latest versions and both produced the same error with several videos from a tutorial that I am trying to archive... I have a decent hardware as well i7 11th gen and 64 GB

**Comment by redzic** [comment]
Can you upload the log file?

**Comment by neoOpus** [comment]
Oddly, the errors disappear when I set the thread per worker to 1 and amount of worker to 2... so I guess there are some bugs in the encoder... but I am still trying to figure out via the settings changes what causes this... here is the specs of the laptop I am using

General specifications
Operating system
Windows 11 Home 64-bit Version: 22000.376

Microprocessor
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

System memory
64 GB

Memory slot 1
32GB A-DATA Technology 3200MHz
Memory slot 2
32GB A-DATA Technology 3200MHz

Video
Graphic device 1
Intel(R) Iris(R) Xe Graphics

Version
30.0.101.1191 (2021-12-03)

Graphic device 2
NVIDIA GeForce MX450

Version
30.0.14.9729 (2021-12-15)
