### ISSUE TITLE
thread main panicked during encode of file

### ISSUE THREAD

**Issue by Gabor-B** [master-of-zen/Av1an#527]
As described above, tested with multiple input files (also this one: https://www.learningcontainer.com/mp4-sample-video-files-download/#). Attaching log files.

Version:
```
av1an 0.3.0-unstable (rev a3eea86) (release)

* Compiler
  rustc 1.57.0 (LLVM 13.0)

* Target Triple
  x86_64-unknown-linux-gnu

* Date Info
   Build Date:  2022-01-11
  Commit Date:  2022-01-11
```

Command
```
docker run --privileged -v "$(pwd):/videos" --user $(id -u):$(id -g) -it --rm av1an/local \
-i $1 --verbose -a=" -c:a libopus -ac 2 -b:a 94k" -v=" --cpu-used=4 --cq-level=24 --threads=8 " -r -s scenes_$1.json -w 8
```
Output
```
INFO [av1an_core::settings] temporary directory: .f105b7a
INFO [av1an_core::settings] resume was set but neither chunks.json nor done.json exist in temporary directory ".f105b7a"
Scene detection
INFO [av1an_core::settings] scenecut: found 8 scene(s) [with extra_splits(240 frames): 8]
  00:00:00 [######################################################################] 100%  462/462 (1270.16 fps, eta 0s) Queue 8 Workers 8 Passes 2
Params: --cpu-used=4 --cq-level=24 --threads=8
  [Worker 1] Pass 2/2 frame   35/0          0B   21481 us 1629.35 fps [ETA  unknown]   13967F
 ........
  [Worker 7] Pass 2/2 frame   32/32     61657B 5222899 us 6.13 fps [ETA  unknown]
  [Worker 8] Pass 2/2 frame   28/28     29274B 1790413 us 15.64 fps [ETA  unknown]
⠴ 00:00:12 [########################################################################] 100%  462/462 (36.82 fps, eta 0s) thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ffmpeg::Error(1381258232: Stream not found)', av1an-core/src/broker.rs:256:70
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/broker.rs:184:35
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', av1an-core/src/settings.rs:1141:21
```
[sample.mp4.log.log](https://github.com/master-of-zen/Av1an/files/7846146/sample.mp4.log.log)

**Comment by redzic** [comment]
Admittedly the error handling for that particular situation could be better, but that issue seems to happen when an old/wrong version of ffmpeg is installed. See #426

**Comment by Gabor-B** [comment]
Ok, as I am using the docker image and reverting to suggested encoders to latest does not work either I will stick to masterofzen:latest...

**Comment by Extarys** [comment]
I've been having this issue for the past 6 months so I've been using latest. Sadly this also means we lose all the changes made to aomenc since then. :/

**Comment by Gabor-B** [comment]
With the latest stable Docker this does not happen anymore, compilation of a correct image is possible
