### ISSUE TITLE
Immediate crash in vapoursynth for all inputs on Linux

### ISSUE THREAD

**Issue by gcp** [master-of-zen/Av1an#563]
Installing the prerequisites (vapoursynth R57 or git master), then cargo install. Trying to encode any video gives

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7e2cf5e in vsscript_createScript () from /usr/local/lib/libvapoursynth-script.so.0
#2  0x0000555555847e25 in vapoursynth::vsscript::environment::Environment::new ()
#3  0x000055555560ceef in core::ops::function::FnOnce::call_once ()
#4  0x0000555555660e9d in once_cell::imp::OnceCell$LT$T$GT$::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h47e81a6121a09f66 ()
#5  0x0000555555764069 in once_cell::imp::initialize_inner ()
#6  0x00005555555ac9ec in once_cell::imp::OnceCell$LT$T$GT$::initialize::h4570c94d2e14aa65 ()
#7  0x00005555555e40aa in av1an_cli::parse_cli ()
#8  0x00005555555e6736 in av1an_cli::run ()
#9  0x00005555555d8dc3 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#10 0x00005555555d8ddd in std::rt::lang_start::{{closure}} ()
#11 0x00005555557fff6b in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> ()
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259
#12 std::panicking::try::do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at library/std/src/panicking.rs:406
#13 std::panicking::try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at library/std/src/panicking.rs:370
#14 std::panic::catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at library/std/src/panic.rs:133
#15 std::rt::lang_start_internal::{closure#2} () at library/std/src/rt.rs:128
#16 std::panicking::try::do_call<std::rt::lang_start_internal::{closure#2}, isize> ()
    at library/std/src/panicking.rs:406
#17 std::panicking::try<isize, std::rt::lang_start_internal::{closure#2}> ()
    at library/std/src/panicking.rs:370
#18 std::panic::catch_unwind<std::rt::lang_start_internal::{closure#2}, isize> ()
    at library/std/src/panic.rs:133
#19 std::rt::lang_start_internal () at library/std/src/rt.rs:128
#20 0x00005555555d8f62 in main ()
```

It looks like I'm not the only one hitting this, see also https://github.com/master-of-zen/Av1an/pull/479

**Comment by gcp** [comment]
Okay, the Linux compilation instructions are missing that you need to install the Python module (pip install vapoursynth), but it's included in the macOS ones.
