### ISSUE TITLE
Crash on Ubuntu 20.04, package libsm6 is required

### ISSUE THREAD

**Issue by veikk0** [master-of-zen/Av1an#62]
I just tried to install & run Av1an in a fresh Ubuntu 20.04 VM. I installed Av1an via pip, but when trying to run Av1an, I got the following error:

    Traceback (most recent call last):
      File "/home/ubuntu/.local/bin/av1an", line 5, in <module>
        from av1an import main
      File "/home/ubuntu/.local/lib/python3.8/site-packages/av1an.py", line 19, in <module>
    import cv2
      File "/home/ubuntu/.local/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
        from .cv2 import *
    ImportError: libSM.so.6: cannot open shared object file: No such file or directory

I installed the distro package `libsm6` to fix the issue.

Didn't run into the same problem as on Ubuntu 18.04 mentioned in #61, and managed fine without installing the distro-provided python3-opencv.

**Comment by master-of-zen** [comment]
https://github.com/master-of-zen/Av1an/commit/c278443ae4a570149acfb31c6eb9e338123f28fd
