### ISSUE TITLE
cv2 error

### ISSUE THREAD

**Issue by mdsohelmia** [master-of-zen/Av1an#901]
av1an -i elephants_dream_original.mp4
Traceback (most recent call last):
  File "/opt/homebrew/bin/av1an", line 5, in <module>
    from av1an import main
  File "/opt/homebrew/lib/python3.11/site-packages/av1an/__init__.py", line 2, in <module>
    from av1an.__main__ import main
  File "/opt/homebrew/lib/python3.11/site-packages/av1an/__main__.py", line 1, in <module>
    from .arg_parse import Args
  File "/opt/homebrew/lib/python3.11/site-packages/av1an/arg_parse.py", line 5, in <module>
    from .project import Project
  File "/opt/homebrew/lib/python3.11/site-packages/av1an/project/__init__.py", line 1, in <module>
    from .Project import Project
  File "/opt/homebrew/lib/python3.11/site-packages/av1an/project/Project.py", line 9, in <module>
    from av1an.utils import frame_probe_fast,  hash_path, terminate
  File "/opt/homebrew/lib/python3.11/site-packages/av1an/utils.py", line 7, in <module>
    import cv2

**Comment by master-of-zen** [comment]
Av1an have been rewritten in rust, try `cargo install av1an`

**Comment by mdsohelmia** [comment]
@master-of-zen  thanks
